# Generated by Django 3.1.2 on 2020-12-07 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prs',
            name='dna_source',
            field=models.CharField(choices=[('23andMe', '23andMe'), ('Ancestry', 'Ancestry'), ('VeritasGenomics', 'Veritas Genomics'), ('CompleteGenomics', 'Complete Genomics'), ('FTDNA', 'Family Tree DNA')], max_length=32),
        ),
    ]
